### ISSUE TITLE
[Feature Request] Piano roll akin to pxtone

### ISSUE THREAD

**Issue by darkhog** [squiggythings/WaveTracker#31]
I think the pianoroll interface is easier to newcomers and people coming from pxtone. Would be nice if Wavetracker would offer piano roll as an option, though obviously more convenient to use that pxtone's. For example, stuff like pitchbends could be done via adjusting a curve visually, same for stuff like effects.

This would offer user a choice between a tracker interface and piano roll, whichever works better for them.

**Comment by bryc** [comment]
Just some thoughts:

A tracker with a piano roll essentially has to act as a "visual editor" for the pattern data itself, and with that comes certain limitations.  Effect commands are not tied to notes directly, so you cannot easily move a note and automatically know which effects to move, not to mention that where you move the note might have no room for effects. Volume column changes can get in the way, instrument changes can get in the way.

I only know of a few trackers that have tried this. Patatracker lets you set or delete note blocks in a grid, but they cannot be directly dragged or resized. Instead, separate Note-Off markers have to be placed, just as you would in a tracker:

![image](https://github.com/user-attachments/assets/25d41d68-56c1-4fc3-a957-119c5c06e288)

At the bottom, it also shows 3 rows for the instrument and two effects, directly assigned to each step. Zooming in/out is not possible with this solution.  And it only lets you see the first 32 steps, I can't even get it to scroll if the pattern has more steps, so maybe it was not finished.

There's also FMComposer (has since been discontinued/deleted from the internet), which _tried_ this, but never fully realized it. It mostly just lets you drag notes up or down to change the pitch, and drag the start and end of each note, but it's buggy and doesn't quite act as you expect. You also can't add new notes in the 'piano roll'.

Buzz does its own thing with a vertical piano roll, but most piano rolls are expected to be horizontal, so that is still difficult to wrap your head around as a DAW user:

![image](https://github.com/user-attachments/assets/11db5fcd-1364-4779-af81-11389fee9ffb)

I'm not against the idea, but it seems like quite a project and may never be able to compete with a piano roll like Reaper or FL.

**Comment by darkhog** [comment]
True, but Wavetracker already has a visualizer, and pianoroll is just one step from that by instead of just displaying data, allow to modify it as well (and maybe rotate it 90 degrees, but that's not really necessary).

**Comment by squiggythings** [comment]
I'm going to close this because it's way beyond the scope of what I would want WaveTracker to be. The existing piano roll visualizer doesn't display the pattern data. It only displays the output of the channels during playback. It has no concept of what waves/instrument/effects are being used at what time, all it knows is pitch and volume. While it certainly would be cool to see, making a piano roll editor would mean building a second editing interface entirely from the ground up, which is something I feel would be better as a separate project than this one.
